version: '3'

services:
  private-api:
    build: .
    container_name: private-api
    env_file:
      - .production.env
    volumes:
      - ./.cache:/.cache
    network_mode: host
    restart: unless-stopped
